version: '3'

services:
  producer:
    build: ./producer
    restart: unless-stopped
    depends_on:
      - kafka
  consumer:
    build: ./consumer
    restart: unless-stopped
    depends_on:
       - kafka
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: 'bitnami/kafka:latest'
    restart: unless-stopped
    ports:
      - '9092:9092'
    depends_on:
        - zookeeper
    logging:
      driver: none
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - AUTO_CREATE_TOPICS_ENABLE=yes